const jwt = require('jsonwebtoken');
const jwksClient = require('jwks-rsa');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

/**
 * Resolve JWT secret:
 *  1. Use WINDY_JWT_SECRET env var if set
 *  2. In production: refuse to start without an explicit secret
 *  3. In dev/test: auto-generate a persistent secret in .env.generated and warn
 */
function resolveJwtSecret() {
  if (process.env.WINDY_JWT_SECRET) {
    return process.env.WINDY_JWT_SECRET;
  }

  const isProduction = process.env.NODE_ENV === 'production';

  if (isProduction) {
    console.error('[jwt-verify] FATAL: WINDY_JWT_SECRET must be set in production. Refusing to start with a default secret.');
    process.exit(1);
  }

  // Dev/test: auto-generate and persist a random secret
  const envFile = path.join(__dirname, '..', '.env.generated');
  try {
    if (fs.existsSync(envFile)) {
      const content = fs.readFileSync(envFile, 'utf-8');
      const match = content.match(/^WINDY_JWT_SECRET=(.+)$/m);
      if (match) {
        console.warn('[jwt-verify] WARNING: Using auto-generated JWT secret from .env.generated. Set WINDY_JWT_SECRET for production.');
        return match[1];
      }
    }
  } catch { /* file read failed, generate new */ }

  const generated = crypto.randomBytes(48).toString('base64url');
  try {
    const line = `# Auto-generated by jwt-verify.js — DO NOT use in production\nWINDY_JWT_SECRET=${generated}\n`;
    fs.writeFileSync(envFile, line, { flag: 'w' });
    console.warn(`[jwt-verify] WARNING: Generated random JWT secret and saved to ${envFile}. Set WINDY_JWT_SECRET for production.`);
  } catch {
    console.warn('[jwt-verify] WARNING: Using ephemeral random JWT secret (could not write .env.generated). Tokens will not persist across restarts.');
  }
  return generated;
}

const JWT_SECRET = resolveJwtSecret();
const CHAT_API_TOKEN = process.env.CHAT_API_TOKEN || '';
const ACCOUNT_SERVER_URL = process.env.WINDY_ACCOUNT_SERVER_URL || 'http://localhost:8098';

// JWKS client with 1-hour cache
const jwks = jwksClient({
  jwksUri: `${ACCOUNT_SERVER_URL}/.well-known/jwks.json`,
  cache: true,
  cacheMaxAge: 60 * 60 * 1000, // 1 hour
  rateLimit: true,
  jwksRequestsPerMinute: 5,
});

function getSigningKey(header) {
  return new Promise((resolve, reject) => {
    jwks.getSigningKey(header.kid, (err, key) => {
      if (err) return reject(err);
      resolve(key.getPublicKey());
    });
  });
}

/**
 * Verify a JWT token. Tries RS256 (JWKS) first, falls back to HS256 (shared secret).
 */
async function verifyToken(token) {
  // Decode header to check algorithm
  const decoded = jwt.decode(token, { complete: true });
  if (!decoded) throw new Error('Invalid token');

  // If the token uses RS256, verify with JWKS
  if (decoded.header.alg === 'RS256') {
    try {
      const publicKey = await getSigningKey(decoded.header);
      return jwt.verify(token, publicKey, { algorithms: ['RS256'] });
    } catch (jwksErr) {
      // Fall back to HS256 shared secret if JWKS fetch fails (development)
      return jwt.verify(token, JWT_SECRET, { algorithms: ['HS256'] });
    }
  }

  // HS256 tokens (development / legacy)
  return jwt.verify(token, JWT_SECRET, { algorithms: ['HS256'] });
}

/**
 * Creates Express middleware that validates JWTs issued by windy-pro account-server.
 * - RS256 via JWKS (production)
 * - HS256 fallback (development)
 * - Static CHAT_API_TOKEN for service-to-service calls
 */
function createAuthMiddleware(options = {}) {
  const { optional = false } = options;

  return async (req, res, next) => {
    const authHeader = req.headers.authorization;

    if (!authHeader) {
      if (optional) return next();
      return res.status(401).json({ error: 'Missing Authorization header' });
    }

    // Static token check (service-to-service)
    if (CHAT_API_TOKEN && authHeader === `Bearer ${CHAT_API_TOKEN}`) {
      req.user = { sub: 'service', role: 'service' };
      return next();
    }

    // JWT check (RS256 via JWKS, fallback to HS256)
    const token = authHeader.replace(/^Bearer\s+/i, '');
    try {
      const decoded = await verifyToken(token);
      req.user = decoded;
      next();
    } catch (err) {
      if (optional) return next();
      return res.status(401).json({ error: 'Invalid or expired token' });
    }
  };
}

module.exports = { createAuthMiddleware, verifyToken };
